### ISSUE TITLE
error on testing angularfire 2

### ISSUE THREAD

**Issue by r-vijay-r** [r-vijay-r/masterbranchproject#3]
@gmanojisaac
created new ng project "ng new masterbranchproject"
installed npm : "npm install"
installed angularfire2 : "npm install firebase angularfire2@2.0.0-beta.5-preview --save-dev"
test run on localhost "ng serve" worked correctly and output obtained "app works!"

changes made in 
src/app/app.component.html
src/app/app.component.ts
src/app/app.module.ts
src/index.html
as per the spreadsheet
saved changes

tested again on localhost "ng serve"
displayed loading.... and then an empty page...

error on checking console 

---

main.bundle.js:39547 EXCEPTION: Error in ./AppComponent class AppComponent_Host - inline template:0:0 caused by: No provider for AngularFire!ErrorHandler.handleError @ main.bundle.js:39547
main.bundle.js:39549 ORIGINAL EXCEPTION: No provider for AngularFire!ErrorHandler.handleError @ main.bundle.js:39549
main.bundle.js:39552 ORIGINAL STACKTRACE:ErrorHandler.handleError @ main.bundle.js:39552
main.bundle.js:39553 Error: No provider for AngularFire!
    at NoProviderError.Error (native)
    at NoProviderError.BaseError [as constructor](http://localhost:4200/main.bundle.js:6281:34)
    at NoProviderError.AbstractProviderError [as constructor](http://localhost:4200/main.bundle.js:39266:16)
    at new NoProviderError (http://localhost:4200/main.bundle.js:39297:16)
    at ReflectiveInjector_._throwOrNull (http://localhost:4200/main.bundle.js:59337:19)
    at ReflectiveInjector_._getByKeyDefault (http://localhost:4200/main.bundle.js:59365:25)
    at ReflectiveInjector_._getByKey (http://localhost:4200/main.bundle.js:59328:25)
    at ReflectiveInjector_.get (http://localhost:4200/main.bundle.js:59137:21)
    at NgModuleInjector.get (http://localhost:4200/main.bundle.js:40181:52)
    at DebugAppView._View_AppComponent_Host0.createInternal (AppComponent_Host.ngfactory.js:16:70)ErrorHandler.handleError @ main.bundle.js:39553
main.bundle.js:39556 ERROR CONTEXT:ErrorHandler.handleError @ main.bundle.js:39556
main.bundle.js:39557 DebugContext_nodeIndex: 0_staticNodeInfo: (...)_tplCol: 0_tplRow: 0_view: _View_AppComponent_Host0_animationListeners: Map_appEl_0: AppElement_currentDebugContext: DebugContext_el_0: app-root_hasExternalHostElement: trueanimationPlayers: ViewAnimationMapcdMode: 4changeDetectorRef: (...)clazz: _View_AppComponent_Host0(viewUtils,parentInjector,declarationEl)componentType: RenderComponentTypecontentChildren: Array[0]context: ObjectdeclarationAppElement: nulldestroyed: (...)flatRootNodes: (...)lastRootNode: (...)numberOfChecks: 0parent: (...)parentInjector: AppModuleInjectorprojectableNodes: Array[0]ref: ViewRef_renderer: DebugDomRendererstaticNodeDebugInfos: Array[1]type: 0viewChildren: Array[0]viewContainerElement: nullviewUtils: ViewUtils__proto__: DebugAppViewcomponent: (...)componentRenderElement: (...)context: (...)injector: (...)providerTokens: (...)references: (...)renderNode: (...)source: (...)**proto**: ObjectErrorHandler.handleError @ main.bundle.js:39557
main.bundle.js:68741 Unhandled Promise rejection: Error in ./AppComponent class AppComponent_Host - inline template:0:0 caused by: No provider for AngularFire! ; Zone: <root> ; Task: Promise.then ; Value: ViewWrappedError Error: No provider for AngularFire!
    at NoProviderError.Error (native)
    at NoProviderError.BaseError [as constructor](http://localhost:4200/main.bundle.js:6281:34)
    at NoProviderError.AbstractProviderError [as constructor](http://localhost:4200/main.bundle.js:39266:16)
    at new NoProviderError (http://localhost:4200/main.bundle.js:39297:16)
    at ReflectiveInjector_._throwOrNull (http://localhost:4200/main.bundle.js:59337:19)
    at ReflectiveInjector_._getByKeyDefault (http://localhost:4200/main.bundle.js:59365:25)
    at ReflectiveInjector_._getByKey (http://localhost:4200/main.bundle.js:59328:25)
    at ReflectiveInjector_.get (http://localhost:4200/main.bundle.js:59137:21)
    at NgModuleInjector.get (http://localhost:4200/main.bundle.js:40181:52)
    at DebugAppView._View_AppComponent_Host0.createInternal (AppComponent_Host.ngfactory.js:16:70)consoleError @ main.bundle.js:68741
main.bundle.js:68743 Error: Uncaught (in promise): Error: Error in ./AppComponent class AppComponent_Host - inline template:0:0 caused by: No provider for AngularFire!(…)consoleError @ main.bundle.js:68743

**Comment by gmanojisaac** [comment]
Vijay.. you need to convert all the steps into individual commits with
descriptive commit messages in a separate branch.
